default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: photog_development

test:
  <<: *default
  database: photog_test

production:
  <<: *default
  database: photog_production
  username: photog
  password: <%= ENV['PHOTOG_DATABASE_PASSWORD'] %>
